language: node_js
node_js:
    - "node"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs


cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  #- npm install -g typedoc typedoc-themes-color typedoc-plugin-nojekyll
  - npm install -g typescript@next ts-node

install:
  - npm install --no-save typedoc typedoc-themes-color typedoc-plugin-nojekyll fs-extra

before_script:
  - echo before_script
script:
  npm run travis
  npm run test
